[tool.poetry]
name = "llm"
version = "0.1.0"
description = ""
authors = ["Arham Jain <arham.nec@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
